### ISSUE TITLE
无法autowire UserMapper

### ISSUE THREAD

**Issue by ygowill** [High128Net/CharlieWebDemo#1]
我是初学者，想学习ssm然后找到了您的博客，我把各个文件中的名字都按照我这边的名字改了，其他的都没有问题，但是无法autowire UserMapper，您能告诉我大概是什么地方出了问题吗
![2018-03-20 1 46 03](https://user-images.githubusercontent.com/29591009/37637919-4752dd1e-2c45-11e8-84d0-d9c817ef425a.png)

**Comment by maolianggen** [comment]
@ygowill 
这种情况，可能Spring配置文件中自动扫描mapper接口的配置没有生效，可检查；如果已经配置，如在本例中所使用的配置方式下，MyBatis接口mapper需要加Repository注解，方可直接在其他层自动装配注入。如下：
![1521530092 1](https://user-images.githubusercontent.com/19165503/37640974-d304ac9a-2c52-11e8-98c4-eda44e527235.jpg)

**Comment by ygowill** [comment]
@High128Net 
加了@Repository之后UserMapper正常了，但是运行的时候出现了以下错误：
No qualifying bean of type 'com.ssm.service.UserService' available（com.ssm和您的com.charlie是一样的）
以及
Error creating bean with name 'userController': Unsatisfied dependency expressed through field 'userService'
您知道问题在哪里吗，麻烦您了

**Comment by maolianggen** [comment]
@ygowill 
1、考虑xml配置文件中是否配置自动扫描service层，且路径是否正确（service层路径下包含接口和实现类）
2、是否在UserService接口的实现类UserServiceImpl中添加Service注解
目测属于第2个问题，如同上一个问题。建议了解 注解方式 的使用

**Comment by heisajoker** [comment]
没有缺失这些注解，但是也不行
